### ISSUE TITLE
Script Not Working

### ISSUE THREAD

**Issue by kang28ivan** [Skamasle/sk_da_importer#1]
Hi, thank you for this script
I try migration from directadmin to vestacp its not working, this stuck proccess on Get Local Database https://prnt.sc/qjvt26 there was no process after I waited for more than 15 minutes

**Comment by cod3r0k** [comment]
Hi @kang28ivan @Skamasle , Isn't it solved ? I want to migrate my DA users to HestiaCP. What should I do now?
